language: python
script: true
deploy:
  provider: pypi
  username: __token__
  password:
    secure: uzyAaHzZmDFc/ohKNGariScGQ7+etPPLspqHFI6Re2DuEU+9+UC8VsGa2O8gi6hm6z3teic2bmezg0Mu8W0X7odd7mw9RUB/I0qPu1UEgc/rzcSTvUyXCXM7m1y7pbGjOgnie8h9vJKxI72L6n64NyvZeWXVZSvhUTtzP7iUNGrdBzOFUTxdCKx0Xs0t+AJS04q0Ju4luclafl29hKrvulFAJoXDcZmiibYQ4DjudS/4I8ZZxaIcnboSA9wM1WiqxTGB0jVgbPJJuu24NC+Fabz1zvylROMOVSqD32vJtkmuom3mZ3HAGOIJgRebojsUkAy85euVfwJGWR+kcKCAYtXgq123vi+lSIKNFW8OLIycg3tKvUrvgkyalArSRkFn2AQFy9TRBy6PTr7TSw6hxUGPLMRCcfb/4bjk9eoK+zHk8Ekw4tOY4riui1hEihDjPmCI52CNfeGdRCb46HTJ+OmbB5QO/d75/unFZfJjRC1PrCAqc+0Mb+kfz+fCvsnhSdUJK74pvZKWGNivlv8Szp2FoxUg2Hc5NDbP/f+T0WCEjVBGEG2/OQgDAjfYNrNeZDH5/qZrEBCKHfBEsYEM/0q68Yg/scMpDIsd1xyAGb/h8ZMwsazGET45LIElIuOMnbICEjXMkBmc5NBDBUK40bi3SkxSh6B8aSpF307dklo=
  distributions: sdist bdist_wheel
  on:
    branch: master
  skip_existing: true
